version: '3'

services:

  pg:
    networks:
      - mynetwork
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres

  nestjsapi:
    ports:
      - "8080:8080"
    depends_on:
      - pg
    networks:
      - mynetwork
    image: nestjsapi
    build:
      context: ./
networks:
  mynetwork: